dbfilename redis_queue.rdb
dir /home/user/Smart_City_V2/backend/v16-bench/config/pids
pidfile /home/user/Smart_City_V2/backend/v16-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /home/user/Smart_City_V2/backend/v16-bench/config/redis_queue.acl
